name: Build project

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  compile-sjs1:
    name: Build project for Scala.js 1.0.0+
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt/boot
            ~/.cache/coursier
            **/target
            !target/sonatype-staging
          key: compile-sjs1-sbt-${{ hashFiles('**/src/main/**/*.scala', 'build.sbt', 'project/*.scala', 'project/*.sbt') }}
          restore-keys: |
            compile-sjs1-sbt-
      - name: Build project
        run: |
          sbt -J-DSCALAJS_VERSION=1.8.0 +compile
  compile-sjs06:
    name: Build project for Scala.js 0.6.xx
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt/boot
            ~/.cache/coursier
            **/target
            !target/sonatype-staging
          key: compile-sjs06-sbt-${{ hashFiles('**/src/main/**/*.scala', 'build.sbt', 'project/*.scala', 'project/*.sbt') }}
          restore-keys: |
            compile-sjs06-sbt-
      - name: Build project
        run: |
          sbt -J-DSCALAJS_VERSION=1.13.1 +compile